#app.secret.key1=${INFISICAL_KEY1}
#app.secret.key2=${INFISICAL_KEY2}

#server.port=8081
# Infisical Configuration
test_token=st.5407e429-2eb6-4e62-835e-eda069349214.bc28ee109ee3bd1579c742541f28fbbc.13e49494a0042f176d556d8c7c9e7ba2
infisical.site-url=http://localhost:80
infisical.project-id=c3413a6d-d4f1-4760-bdb8-7e87caf0174f
infisical.env-slug=spring-infisical-demo-vh98
db.name=${db_name}
db.password=${password}
db.username=${username}